const errorCodes = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DELETED: 'USER_DELETED',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ALREADY_VERIFIED: 'USER_ALREADY_VERIFIED',
  INVALID_EMAIL_CODE: 'INVALID_EMAIL_CODE',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
};
module.exports = errorCodes;
